import { COMPANY } from '../config/company'
import { formatCurrency, formatDate } from './format'

export function computeTotals(quote) {
  const subtotal = (quote.lineItems || []).reduce((sum, li) => sum + Number(li.qty || 0) * Number(li.unitPrice || 0), 0)
  const markup = subtotal * (Number(quote.markupPct || 0) / 100)
  const preGst = subtotal + markup
  const gst = preGst * (Number(quote.gstPct || 0) / 100)
  const total = preGst + gst
  return { subtotal, markup, preGst, gst, total }
}

// Opens a clean, print-ready quotation in a new window and triggers the browser
// print dialog (Save as PDF). No backend / PDF library needed for the prototype.
export function exportQuotePdf(quote) {
  const t = computeTotals(quote)
  const rows = quote.lineItems.map((li, i) => `
    <tr>
      <td>${i + 1}</td>
      <td>${li.desc}</td>
      <td class="r">${li.qty}</td>
      <td>${li.unit}</td>
      <td class="r">${formatCurrency(li.unitPrice)}</td>
      <td class="r">${formatCurrency(li.qty * li.unitPrice)}</td>
    </tr>`).join('')

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${quote.quoteNo}</title>
    <style>
      * { font-family: 'Helvetica Neue', Arial, sans-serif; color: #111827; box-sizing: border-box; }
      body { margin: 40px; font-size: 13px; }
      .head { display:flex; justify-content:space-between; border-bottom:3px solid #4F46E5; padding-bottom:16px; margin-bottom:24px; }
      .brand { font-size: 22px; font-weight: 800; color:#4F46E5; }
      h1 { font-size: 20px; margin: 0 0 4px; }
      .muted { color:#6B7280; }
      table { width:100%; border-collapse: collapse; margin-top: 16px; }
      th { text-align:left; background:#F3F4F6; padding:8px; font-size:11px; text-transform:uppercase; letter-spacing:.04em; color:#6B7280; }
      td { padding:8px; border-bottom:1px solid #E5E7EB; }
      .r { text-align:right; }
      .totals { width: 300px; margin-left:auto; margin-top:16px; }
      .totals td { border:none; padding:4px 8px; }
      .grand { font-weight:800; font-size:15px; border-top:2px solid #111827; }
      .verify { margin-top:32px; padding:12px 16px; background:#DCFCE7; border-radius:8px; font-size:12px; }
      .foot { margin-top:40px; font-size:11px; color:#9CA3AF; }
      @media print { body { margin: 16mm; } }
    </style></head><body>
    <div class="head">
      <div>
        <div class="brand">TenderQuick</div>
        <div class="muted">${COMPANY.name}</div>
        <div class="muted">${COMPANY.address}</div>
        <div class="muted">UEN ${COMPANY.uen} · GST ${COMPANY.gstReg}</div>
      </div>
      <div style="text-align:right">
        <h1>QUOTATION</h1>
        <div><b>${quote.quoteNo}</b></div>
        <div class="muted">${formatDate(new Date().toISOString())}</div>
      </div>
    </div>
    <div style="display:flex; justify-content:space-between;">
      <div>
        <div class="muted">Prepared for</div>
        <div><b>${quote.client}</b></div>
        <div class="muted">Tender ${quote.tenderRef}</div>
      </div>
      <div style="text-align:right">
        <div class="muted">Subject</div>
        <div><b>${quote.title}</b></div>
      </div>
    </div>
    <table>
      <thead><tr><th>#</th><th>Description</th><th class="r">Qty</th><th>Unit</th><th class="r">Unit Price</th><th class="r">Amount</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <table class="totals">
      <tr><td>Subtotal</td><td class="r">${formatCurrency(t.subtotal)}</td></tr>
      <tr><td>Margin (${quote.markupPct}%)</td><td class="r">${formatCurrency(t.markup)}</td></tr>
      <tr><td>GST (${quote.gstPct}%)</td><td class="r">${formatCurrency(t.gst)}</td></tr>
      <tr class="grand"><td>Total (SGD)</td><td class="r">${formatCurrency(t.total)}</td></tr>
    </table>
    ${quote.verified ? `<div class="verify">✓ Reviewed and verified by ${quote.verifiedBy} (human check completed).</div>` : ''}
    <div class="foot">This quotation is valid for 30 days. Generated by TenderQuick · ${COMPANY.email} · ${COMPANY.phone}</div>
    <script>window.onload = function(){ setTimeout(function(){ window.print(); }, 300); };</script>
    </body></html>`

  const w = window.open('', '_blank', 'width=900,height=1000')
  if (!w) return false
  w.document.write(html)
  w.document.close()
  return true
}
